hack4impact-calpoly/surfrider

README.md, package-lock.json, src/database/db.ts
=> repo setup

package-lock.json, package.json
=> install zod

package-lock.json, package.json
Closes N/A
There was a security vulnerability in earlier versions of Nextjs 14 so I upgraded all npm packages to their latest versions.
- Upgraded npm packages
Build
=> update all packages to latest minor version

src/schema/egrid.ts
Closes N/A
Adding the egrid schema types as an example since it'll be used across many different tasks
- Defined schema types for egrid
Build
=> create egrid helper types

test/app/example/page.test.tsx
Closes #12 
Created unit tests for the `/example` page
Created test file.
Ran unit tests.
=> test: add unit tests for example page

.vscode/settings.json, README.md, package-lock.json, src/app/nickaan04/page.tsx, test/app/nickaan04/page.test.tsx
Closes N/A
Created a stateful counter button with unit tests and updated README
Created counter button on a new page
Wrote unit tests to validate button functionality
Updated README.md with my name, LinkedIn profile, and team position
Ran unit tests for initializing the button count to 0 and incrementing the button on a click
=> Completed intro task

.github/workflows/ci.yml
Closes #7 
Fix CodeQL vulnerability with CI script permissions.
Added top level-permissions declaration to Actions CI script.
CI script runs successfully
=> fix: ci script permissions

README.md, src/app/henryhorse/page.tsx, test/app/henryhorse/page.test.tsx
Closes #4 
Pull request for intro task of making a button page
Created /src/app/henryhorse/page.tsx
Has a button that when clicked increments a counter
Created /test/app/henryhorse/page.test.tsx
Tests button incrementing
Modified README.md
Added my name
I tested whether or not the number changed on the button when you increment it.
=> feat: added HenryHorse button page

README.md
Closes N/A
Added designer linkedins to readme
Added designer linkedins to readme
N/A
=> docs: add designer linkedin links to readme

.github/workflows/ci.yml
Closes N/A
Add Next.js build caching to the CI workflow - https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
Add Next.js build caching to `.github/workflows/ci.yml`
Ensured CI workflow runs correctly
=> ci: add next.js build caching

README.md, src/app/lindsayminami/page.tsx, test/app/lindsayminami/page.test.tsx
Issue #4 
Finish the intro task by adding button that counts and name to readme.
- /src/app/lindsayminami/page.tsx
- button works
- link to linkedin works
=> Lindsay's Intro

src/database/egrid-schema.ts
Closes #20 
Defined a Mongoose schema for eGRID data, specified by the columns in the US22, SRL22, and ST22 excel sheets.
Created a new file `/src/database/egrid-schema.ts`
Converted column names from US22, SRL22, and ST22 sheets into schema attributes, assigning appropriate data types
Included `EgridSchema` definition and `Egrid` model export
No tests
No screenshots
=> Created eGRID schema

src/database/egrid-schema.ts
Closes N/A
Renamed `Egrid` to `EgridModel` for clarity
- `/src/database/egrid-schema.ts`
None
=> chore: rename egrid model

src/schema/formula.ts
Closes #21
Created a Zod schema object to represent formulas within the calculator.
src/schema/formula.ts, added Zod object.
NA
=> feat: zod object for Formmula

src/schema/error.ts
Closes #35
Created shared error type.
src/schema/error.ts
added shared error types to this file
NA
=> feat: created shared error type

src/database/egrid-schema.ts
Closes #37
Created with a compound index on the key(year) and location properties for the egrid schema. 
/src/database/egrid-schema.ts - added compound index
Could verify that the properties are listed in the correct order.
=>  Add indexing and validation to egrid schema

src/app/api/avert/route.ts, vercel.json
Closes #49 
Added cronjob and the GET route with the print statement. 
created `avert/route.ts`
modified `vercel.json`
Ryan (Chan) mentioned that I wouldn't be able to test this -- please let me know if I should. 
=> Added Cronjob and GET Log

src/database/avert-schema.ts
Closes #44 
Defined a Mongoose schema for Avert data, specified by the sections in the 2023 and Capacity Factor excel sheets.
Created a new file `/src/database/avert-schema.ts`
Converted sections names into schema attributes, assigning appropriate data types
Included AvertSchema definition and Avert model export
No tests
No screenshots
=> Created Avert Schema

src/database/avert-model.ts, src/database/egrid-model.ts
Closes #55
Create index for AVERT schema.
=> Avert-index

package-lock.json, package.json, src/app/api/egrid/route.ts, src/services/egrid-service.ts
Closes #24 
Add fetch, transform, and calling functions for egrid data
- /api/egrid/route.ts (calling function to fetch and transform)
- /src/services/egrid-service.ts (fetching and transforming functions for the data)
- make sure the data is correct and it's the correct formatting that you hand wanted
=> feat: add fetch, transform and calling functions for 2022 egrid data

src/services/egrid-store.ts
Closes #48
Modifies the functions in /services/egrid-store.ts to return the new Error instead of throwing the EgridServiceError
/services/egrid-store.ts
- ensure that the Errors are correctly returned and formatted when an error occurs. 
=> feat: removed previous error thrown and added updated Error

src/schema/avert.ts, src/services/avert-store.ts, test/schema/avert.test.ts
Closes N/A
Didn't catch this in PR
=> fix: avert service layer

src/schema/error.ts, src/services/avert-store.ts, src/services/egrid-store.ts, src/utils/errors.ts, test/schema/error.test.ts, test/utils/errors.test.ts
Closes #81
Created a uniform error handling system that folds different types of errors into a single class.
Unit tests
=> Robust-errors

src/utils/formula-collection.ts, src/utils/formula-parser.ts, test/mocks/formula-mocks.ts, test/utils/formula-collection.spec.ts
Closes #58 
Converted equations 1-10 from the Impact Calculator to Formulas for the FormulaParser
Added formula-collection.ts which has the first 10 formulas
Added formula-collection.spec.ts to test the first 10 formulas
I compared the values produced by the FormulaParser with the values on the spreadsheet, with some percent error leeway as the spreadsheet rounds in intermediate steps, whereas the FormulaParser calculates the exact value (although potentially with other minor variations like precision errors).
=> 58 start formula implementation

.github/workflows/ci.yml
=> feat: merge queue

src/schema/formula.ts, src/services/egrid-fetch.ts, src/utils/formula-collection.ts, src/utils/formula-parser.ts, test/schema/formula.test.ts, test/utils/formula-collection.spec.ts
=> Formula-restructure

src/database/avert-model.ts, test/mocks/avert-mocks.ts, test/schema/avert.test.ts
=> chore: clean up avert schema and tests

jest.config.ts
Closes #50 
Modified jest to run coverage on all source files in src/
Changed collectCoverageFrom and coverageThreshold in jest.config.ts 
I ran npm test and got a coverage report back
=> chore: updated Jest config to collect coverage from src/

README.md, src/app/Velevynn/page.tsx, test/app/Velevynn/page.test.tsx
Closes #4 
Implement a stateful counter button with its corresponding jest unit tests.
Included LinkedIn in README file
Added src/app/Velevynn/page.tsx -> Implement stateful counter button
Added test/app/ishavarrier/page.test.tsx -> Jest tests for button loading and counting
Updated README.md with name, LinkedIn link, and role.
Tested loading of button, its counter, and the display text, as well as multiple increments of the button counter.
N/A
=> Velevynn intro

src/formulas/formula-collection.ts, src/schema/formula-id.ts, test/formulas/formula-collection.spec.ts
Closes #75
Added formulas #22 - 27
src/formulas/formula-collection.ts - added in the formulas themselves
src/schema/formula-id.ts - added the formulas to the type definition
test/formulas/formula-collection.spec.ts - tested each formula with value in spreadsheet
Tested each formula, perhaps try to test with different values. 
=> #75 implement formulas 22 27

src/app/page.tsx, src/components/results.tsx, src/components/ssp-fields.tsx
Closes N/A
Fix type safety for SSP components by removing non-null assertions
SSP fields and related
Unit tests and localhost
=> fix: type safety for ssp components

src/app/layout.tsx, src/components/calculator.tsx
Closes N/A
Background color cutting off when scrolling top/bottom of screen
=> fix: background color cutoff
